# Vocabulary tables {#sec-omop_vocabularies}


```{r, warning=FALSE, message=FALSE}
library(DBI)
library(dbplyr)
library(dplyr)
library(here)
library(CDMConnector)
library(ggplot2)
library(clock)
```

```{r}
db<-dbConnect(duckdb::duckdb(), 
              dbdir = eunomiaDir(datasetName = "synthea-covid19-10k"))
cdm <- cdmFromCon(db, cdmSchema = "main", writeSchema = "main", writePrefix = "my_study_")
```

```{r, echo = TRUE}
cdm
```


## Concept

## Concept ancestor
## Counting records

What's the number of condition occurrence records per person in the database? We can find this out like so

```{r, echo = TRUE}
cdm$person |> 
  left_join(cdm$condition_occurrence |> 
  group_by(person_id) |> 
  count(name = "condition_occurrence_records"),
  by="person_id") |> 
  mutate(condition_occurrence_records = if_else(
    is.na(condition_occurrence_records), 0,
    condition_occurrence_records)) |> 
  group_by(condition_occurrence_records) |>
  count() |> 
  collect() |> 
  ggplot() +
  geom_col(aes(condition_occurrence_records, n)) +
  theme_bw()
```

How about we were interested in getting record counts for some specific concepts related to Covid-19 symptoms?

```{r, echo = TRUE}
cdm$condition_occurrence |> 
  filter(condition_concept_id %in% c(437663,437390,31967,
                                     4289517,4223659, 312437,
                                     434490,254761,77074)) |> 
  group_by(condition_concept_id) |> 
  count() |> 
  left_join(cdm$concept,
            by=c("condition_concept_id" = "concept_id")) |> 
  collect() |> 
  ggplot() +
  geom_col(aes(concept_name, n)) +
  theme_bw()+
  xlab("")

```