---
title: "Working with the OMOP CDM from R"
---

In this second half of the book we will see how we can work with data in the OMOP CDM format from R.

-   In @sec-cdm_reference we will see how to create a cdm_reference in R, a data model that contains references to the OMOP CDM tables and provides the foundation for analysis.

-   The OMOP CDM is a person-centric model, and the person and observation period tables are two key tables for any analysis. In @sec-omop_person_obs_period we will see more on how these tables can be used as the starting point for identifying your study participants.

-   The OMOP CDM standarises the content of health care data via the OMOP CDM vocabulary tables, which provides a set of standard concepts to represent different clinical events. The vocabulary tables are described in @sec-omop_vocabularies, with these tables playing a fundamental role when we identify the clinical events of interest for our study.

-   Clinical records associated with individuals are spread across various OMOP CDM tables, covering various domains. In @sec-omop_clinical_tables we will see how these tables represent events and link back to the person and vocabulary tables.
