# Working with the OMOP CDM from R

In this second half of the book, we will focus on how we can work with data in the OMOP CDM format from R.

-   In @sec-cdm_reference we will see how to create a cdm_reference in R, a data model that contains references to the OMOP CDM tables and provides the foundation for analysis.

-   The OMOP CDM is a person-centric model, and the person and observation period tables are two key tables for any analysis. In @sec-exploring_the_cdm we will see more on how these tables can be used as the starting point for identifying your study participants.

-   In @sec-adding_features we will see how to add demographics information to different tables of interest and summarise it using dplyr code. Finally, we will also see how to use tidyverse verbs to add some custom features.

-   In @sec-creating_cohorts we will have a look at the cohort object, how it is defined and what are their attributes. We will also see how to create some simple base cohorts and apply some inclusion criteria to them.

-   Finally, in @sec-working_with_cohorts we will learn how to intersect cohorts with one another, extracting counts, presence indicators, specific dates, or time differences to obtain the information of interest for our study population.
